### ISSUE TITLE
week6 blog post not loading

### ISSUE THREAD

**Issue by sajarin** [hunter-college-ossd-fall-2019/sajarindider-weekly#1]
I'm not quite sure why but my blog post for week 6 is not viewable via the blog, despite the fact that I can clearly see that I successfully committed and pushed the changes. Curiously, my contributions.md file updated perfected. 

Hopefully, I can troubleshoot this but if anyone has any clues as to what the problem could be I'd greatly appreciate any help.

**Comment by stewartweiss** [comment]
The one thing I noticed is that the character encoding is windows-1252, not UTF-8. I wonder whether this is the problem.  I assume you wrote this on a Windows host. Convert to UTF-8 either by uploading onto a Linux host and running
`dos2unix blogfile`
or making a change in GitHub's editor and committing.

**Comment by sajarin** [comment]
Yes, the issue was the file encoding. I managed to resolve the issue. You should be able to view blog6 now. Apologies for the inconvenience and thank you for pointing out the error. I'll make sure to write my blog posts on my linux machine from now on!
